apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/development-and-testing-451513/cluster1/backend:latest
        ports:
        - containerPort: 3000