name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: development-and-testing-451513

      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin || gcloud components install gke-gcloud-auth-plugin

      - name: Configure Kubernetes
        run: |
          gcloud container clusters get-credentials cluster-1 --zone asia-south1-c --project development-and-testing-451513

      # ✅ Build & Push Backend Image
      - name: Build & Push Backend Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/development-and-testing-451513/cluster1/backend:latest backend/
          docker push asia-south1-docker.pkg.dev/development-and-testing-451513/cluster1/backend:latest

      # ✅ Deploy Backend to Kubernetes
      - name: Deploy Backend to Kubernetes
        run: |
          kubectl apply -f backend/

      # ✅ Build & Push Frontend Image
      - name: Build & Push Frontend Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/development-and-testing-451513/cluster1/frontend:latest frontend/
          docker push asia-south1-docker.pkg.dev/development-and-testing-451513/cluster1/frontend:latest

      # ✅ Deploy Frontend to Kubernetes
      - name: Deploy Frontend to Kubernetes
        run: |
          kubectl apply -f frontend/
